[package]
name = "zim-sys"
version = "0.1.0"
edition = "2021"
links =  "zim"

[dependencies]
cxx = "1.0.78"

[build-dependencies]
cxx-build = "1.0.78"

[target.'cfg(target_family = "unix")'.build-dependencies]
pkg-config = "0.3.25"
