[package]
name = "zim-sys"
version = "0.1.0"
edition = "2021"
links =  "zim"

[dependencies]

[build-dependencies]
bindgen = "0.60.1"

[target.'cfg(target_family = "unix")'.build-dependencies]
pkg-config = "0.3.25"
